drop table if exists tb_user cascade;


create table tb_user
(
    id    bigint generated by default as identity,
    email varchar(255) not null,
    name  varchar(255) not null,
    city  varchar(255) not null,
    home_number  varchar(255) not null,
    phone_number  varchar(255) not null,
    state  varchar(255) not null,
    street_name  varchar(255) not null,
    zip_code  varchar(255) not null,
    primary key (id)
);



INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 1', 'vinicius@gmail.com', 'Atlanta', '356', '6722939175', 'NY', 'Rua Marina', '12070080');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 2', 'martin@gmail.com', 'Campinas', '750', '7538556664', 'NY', 'Rua Zaqueu', '11702300');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 3', 'robert@gmail.com', 'Islandia', '336', '1330662716', 'NY', 'Rua Jorlan', '13505142');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 4', 'cesar@gmail.com', 'BayShore', '666', '2422775733', 'NY', 'Rua Jacyra', '14710064');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 5', 'heloisa@gmail.com', 'Happuagge', '777', '5538660653', 'NY', 'Rua Jose', '11088175');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 6', 'maria@gmail.com', 'Aricans', '483', '7238151303', 'NY', 'Rua Jesus', '07791250');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 7', 'giovana@gmail.com', 'Cosmopolis', '12', '2528545225', 'NY', 'Av Alabama', '08550130');
INSERT INTO tb_user (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Test user 8', 'raquel@gmail.com', 'Rio Claro', '046', '4732688818', 'NY', 'Via Tiete', '14106056');

